modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/moonfather1/tearsofgaia" #optional


[[mods]] #mandatory
modId="tearsofgaia" #mandatory
version="1.1" #mandatory
displayName="Tears of Gaia" #mandatory


#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://modrinth.com/mod/tearsofgaia" #optional
logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="MoonFather" #optional

description='''Adds four gems that can be used on an anvil to strengthen your tools. 
The mod is intended to add some tool diversity by using what you have (gems are rare), not the same best set always. '''

[[dependencies.tearsofgaia]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tearsofgaia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
